### ISSUE TITLE
How to sort the Chinese catalogue？

### ISSUE THREAD

**Issue by zhoujiayaoo** [SebastianMC/obsidian-custom-sort#40] opened 2022-12-14 16:09 UTC
How to set the Chinese directory at the bottom and English directory at the top?

**Comment by zhou-jiayao** [comment] 2022-12-14 16:45
I use the following configuration

---
sorting-spec: |
    target-folder: /*
    /folders
    > true a-z

---

But here's what happened
![image](https://user-images.githubusercontent.com/84183976/207656076-43e2c83a-ef93-426e-8932-cea8cd503d7f.png)

I don't think that's reasonable，Thank you very much for your Chinese support.

**Comment by SebastianMC** [comment] 2022-12-15 11:52
Hi @zhou-jiayao 

I tried to reproduce an equivalent example locally. Take a look at the content of `sortspec` note below. I assume it is exactly the same on your computer, indentation matters - when you copied & pasted the example sortspec the indentation got lost. So the below `sortspec` content is my best-guess of the specification on your machine:

```yaml
---
sorting-spec: |  
 target-folder: /*  
 /folders  
  > true a-z
---
```

with that sorting specification the order of File Explorer items in my test vault is:

<img width="645" alt="2022-12-15_12-28-57" src="https://user-images.githubusercontent.com/23032356/207849188-fb41477c-b4b6-4a9d-9f8d-fef1dec4b262.png">

and for me it looks that the order of folders and files exactly matches the specification:
- first go the folders, sorted - as specified - using the reverse true alphabetical order.
  - that means, the chinese characters (words) go before english words. Technically that's how the platform sorting works - obsidian and the custom sort plugin directly invoke platform sorting functions and fully rely on them
- then, below folders, go the notes (files)

If you change the sorting order to (ascending) true alphabetical (change of `>` into `>` in the above example):

```yaml
---
sorting-spec: |  
 target-folder: /*  
 /folders  
  < true a-z
---
```

you get the previous order of folders reversed:

 <img width="623" alt="2022-12-15_12-28-39" src="https://user-images.githubusercontent.com/23032356/207850392-8ec9e01d-7172-47c0-8b88-6a7d319f4ed5.png">

Does this clarification help?

And let me emphasise: Obsidian itself and the custom-sort plugin directly invoke platform sorting functions and fully rely on them (the so-called `Collator`). There is no internal custom code which examines the folder and notes titles to determine the order - it is delegated to the platform. I don't have much experience with Chinese and I have no idea what is the standard behavior of sorting. I believe that any system-wide customisation of locale and sorting will have influence on ordering of items in Obsidian. 

If you want me to run your example on my machine, please:
- send me the folder names and note titles as text here (I was unable to grab the actual text from your screenshot)
- send me an additional screenshot of the order of items when the custom-sort plugin is not active (or not enabled or not installed) with the information of which Obsidian sorting is selected (in the dropdown)

**Comment by zhou-jiayao** [comment] 2022-12-16 01:45
First of all, thank you very much for your reply.
Your configuration here achieves exactly what I want.
![image](https://user-images.githubusercontent.com/84183976/208002333-5cf5667d-6f1a-4c27-8dcc-3e842f5fc809.png)

But I have the same configuration as you, and it shows the following result：
![image](https://user-images.githubusercontent.com/84183976/208002464-3394330d-1177-45bb-a162-f3a6d0a1dd0e.png)

That is, the file or directory with the Chinese title is always at the front, but I want it to be at the bottom, as you have implemented.

`
---
sorting-spec: |  
 target-folder: /*  
 /folders  
  < true a-z
---
`
My configuration is exactly the same as yours, and the Chinese and English names are also regular, so I won't send you the complete configuration.

Looking forward to your reply again.

**Comment by zhou-jiayao** [comment] 2022-12-16 01:46
Sorry, I am not good at using github reply, the format configured above is wrong, I will send it again.

`
sorting-spec: |  
 target-folder: /*  
 /folders  
  < true a-z
`

**Comment by zhou-jiayao** [comment] 2022-12-16 01:47
Sorry, I am not good at using github reply, the format configured above is wrong, I will send it again.
```yaml
sorting-spec: |  
 target-folder: /*  
 /folders  
  < true a-z
```

**Comment by SebastianMC** [comment] 2022-12-18 19:28
It looks that a kind of comment-based remote debugging session is needed :-)
I suspect that your machine is configured in some way to produce the sorting order which you observe.
Let's confirm that first.
When I examine the vault folder from the system file explorer (which is finder app on macOS) I see the following behavior:

<img width="192" alt="2022-12-18_19-56-17" src="https://user-images.githubusercontent.com/23032356/208315470-5f3cdc72-4a1e-48c7-a954-a129a2cf0fc1.png">

the above image shows alphabetical sorting by name.
The second image below shows reverse alphabetical sorting by name:

<img width="190" alt="2022-12-18_19-56-43" src="https://user-images.githubusercontent.com/23032356/208315506-efb5e269-9882-45b6-a40d-b4ff7dc6115b.png">

as you can see, it is similar to what I observe at the Obsidian level on my side.

Could you please confirm, what you see in the system file explorer on your side?
Also, when you turn off the custom-sort plugin in your vault, how the standard A-Z and Z-A sorting of Obsidian orders the folder and notes?

I'm trying to figure out if reaching the desired sorting order would require overriding of system/standard or not

**Comment by SebastianMC** [comment] 2023-02-13 17:34
Hi @zhoujiayaoo 

not having further input from you since Dev '22, I'm closing the ticket.
Feel free to reopen it if we can proceed

thanks,
Seb

**Closed by SebastianMC** 2023-02-13 17:34 UTC
