### ISSUE TITLE
Custom sorting not respected, directory changes not reflected in tree, directory tree disappears (Obsidian Desktop v1.5.4)

### ISSUE THREAD

**Issue by FitzFrobozz** [SebastianMC/obsidian-custom-sort#131] opened 2024-02-06 21:30 UTC
[**Note:** For all I know, this could be more than one bug. If anyone has a compelling reason to think that this is actually the case, let me know if there is anything I can do on my end.]

After applying the Obsidian 1.5.4 update this morning (**Insider release**), I've experienced the following issues:

**1. Custom sorting not respected.** Sorting notification displays as usual, but the sorting definition isn't being respected.
 - **Workaround:** Persists no matter what, no workaround found so far.

**2. Directory changes not reflected in tree.** When I drag a folder into another folder, the file tree does not show the change.
 - **Workaround:** Corrected by disabling the plugin and relaunching Obsidian, but issue recurs when I move another folder.

**3. Directory tree disappears.** When I launch or relaunch Obsidian, the directory tree is initially not shown at all.
 - **Workaround:** none found yet

Error shown in Console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'sortOrder')
    at t.jt (plugin:custom-sort:6:11144)
    at t.eval (plugin:custom-sort:42:7319)
    at t.a (plugin:custom-sort:6:802)
    at t.sort (app.js:1:2417538)
    at app.js:1:2768711
    at e.onNextFrame (app.js:1:2768586)
```

**Comment by claremacrae** [comment] 2024-02-06 21:50
@FitzFrobozz - to help the author out, it's worth noting that you are using an Obsidian Insider release, which is not available to all, and perhaps the author does not have access.

**Comment by FitzFrobozz** [comment] 2024-02-06 21:52
I put the Obsidian version number in the issue title and at the top of the issue, but I'll highlight that somehow. Thanks.

**Comment by FitzFrobozz** [comment] 2024-02-06 22:04
> @FitzFrobozz - to help the author out, it's worth noting that you are using an Obsidian Insider release, which is not available to all, and perhaps the author does not have access.

I put the Obsidian version number in the issue title and at the top of the issue, but I just highlight that it's an Insider release version. Thanks, Claire.

**Comment by claremacrae** [comment] 2024-02-06 22:15
@SebastianMC Whilst there’s of course no expectation that reports are fixed at all, yet alone with Insider builds … if you don’t have an Insider licence (or whatever it’s called) I have a lot of Obsidian credit courtesy of a couple of Obsidian October past events, and would be happy to donate you an Insider license, for your own interest. 

If this would help, please email my address in my github profile from your email used in your (free) Obsidian account. Cheers.

**Comment by aicayzer** [comment] 2024-02-07 15:06
Adding to this already very well documented issue, here's an extract from the console. 
![Obsidian (Screenshot 000967)@2x](https://github.com/SebastianMC/obsidian-custom-sort/assets/22304629/9628d69f-d9e0-44ab-b8c7-ecccf32cff35)

and here's what the app looks like when launched with the plugin `enabled`
![Obsidian (Screenshot 000971)@2x](https://github.com/SebastianMC/obsidian-custom-sort/assets/22304629/18c6385e-120a-4a10-864a-2f115954fb4c)

and when the plugin is `disabled`
![Obsidian (Screenshot 000969)@2x](https://github.com/SebastianMC/obsidian-custom-sort/assets/22304629/5eec0c9b-7604-4d50-abcb-eed543c12d99)

Echoing @claremacrae's comment, no expectation of an immediate fix! Super grateful for your work to date.

**Comment by aicayzer** [comment] 2024-02-07 15:09
Ahhh and having just read the release notes, the last few lines shed a little light on why an issue's occurred: 

## Breaking changes
==File Explorer and Tags pane both received a small code refactor. This might affect some plugins that rely on the internal JS structure. Themes should not be affected.==
Tags can no longer end in a /.

**Comment by SebastianMC** [comment] 2024-02-07 22:54
Hi @FitzFrobozz , @claremacrae , @aicayzer 

Thank you @FitzFrobozz for reporting the problem with details!

Thank you @claremacrae and @aicayzer for your contribution!

Thanks @claremacrae for the Insider license offer - I already own one, just being busy with my regular work obligations I didn't have a chance to update and encounter the issue by myself.

Please update to [2.1.6 release](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.6) and confirm if it works on your side. It contains the bugfix for this specific problem, resulting - as you suspected - from the refactoring of internal Obsidian JS structure around the File Explorer.

**Comment by aicayzer** [comment] 2024-02-07 23:13
Thanks so much @SebastianMC, fix worked perfectly :)

**Comment by FitzFrobozz** [comment] 2024-02-08 02:29
> Please update to [2.1.6 release](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.6) and confirm if it works on your side. It contains the bugfix for this specific problem, resulting - as you suspected - from the refactoring of internal Obsidian JS structure around the File Explorer.

Yep, smooth as glass. Thanks so much! I realize trying to support Insider builds could be like working with a moving target, so going above and beyond like this is much appreciated.

**Comment by FitzFrobozz** [comment] 2024-02-08 20:34
Hmm, maybe I spoke too soon? Either I overlooked this somehow in my retest above, or this is new (I'm leaning toward the former, for which I sincerely apologize!), but in any event  # 1 & 2 above are recurring again today, but with a twist on # 1:

"1. Custom sorting not respected": I'm now noticing that *new* sorting specifications are being ignored, while yesterday's (which predated Insider v1.5.4) are still being respected.

"2. Directory changes not reflected in tree": same behavior as before, and an Obsidian restart works around the issue.

This is the only error I'm seeing now (different from the above):
```
Uncaught TypeError: Cannot set properties of undefined (setting 'parent')
    at e.addChild (app.js:1:1253924)
    at e.setChildren (app.js:1:1254034)
    at t.jt (plugin:custom-sort:6:11251)
    at t.eval (plugin:custom-sort:42:7319)
    at t.a [as sort] (plugin:custom-sort:6:802)
    at t.sort (app.js:1:2417538)
    at app.js:1:2768711
    at e.onNextFrame (app.js:1:2768586)
```

And for what it's worth, I'm 100% sure that "3. Directory tree disappears" is not recurring.

**Comment by SebastianMC** [comment] 2024-02-09 11:04
Hi @FitzFrobozz,

thanks for reporting the problems!
It gives a chance to fix it before it reaches the public release.

Following your report I did a more thorough testing and it confirms your observations.

Technically it looks that the breaking JS changes in Obsidian File Explorer which they made in insider version 1.5.4 are not trivial to address on plugin side.

I removed the 2.1.6 release of custom-sort and added a warning box to README here on github asking the users not to update Obsidian.

I will keep you posted here about any progress.

**Comment by SebastianMC** [comment] 2024-02-09 13:28
Hi @FitzFrobozz 

Please update the plugin to [release 2.1.7](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.7) - exposed a minute ago.

A deeper round of reverse engineering of Obsidian was required to introduce a fix which addresses the problem and is compatible both with 1.5.4 and prior versions of Obsidian

Please let me know if it works for you

**Comment by aicayzer** [comment] 2024-02-10 16:02
Working for me :)

**Comment by SebastianMC** [comment] 2024-02-21 11:16
No further feedback from @FitzFrobozz (the reporter of this issue) since two weeks. I'm about to close this issue in a week or so, it works for me, also @aicayzer confirmed. And also I'm confident with the fix after a deeper round of re-engineering of the recent Obsidian source code.

**Comment by stausmar** [comment] 2024-02-23 17:40
I can confirm that the latest update fixed this issue. Thanks a lot!

**Closed** 2024-02-23 19:18 UTC
Labels: bug, CRITICAL
