### ISSUE TITLE
Update and install problem

### ISSUE THREAD

**Issue by merlinuwe** [SebastianMC/obsidian-custom-sort#39] opened 2022-12-05 21:04 UTC
Hi, 

I tried to update (1.2 --> 1.3) your nice plugin with 

![image](https://user-images.githubusercontent.com/4138869/205741886-8db8bc14-5456-48ea-b189-ecc707201c83.png)

but I get the message:

![image](https://user-images.githubusercontent.com/4138869/205742077-a9da7d9c-f698-445e-a5c7-62d665bee636.png)

I wanted to start from scratch, so I deleted the plugin Folder and I removed the file sortspec.md

Now it is not possible to install it again. What can I do?

**Comment by alecthegeek** [comment] 2022-12-06 02:25
same on en_AU environment (I've never had the plugin installed)

**Comment by skvale** [comment] 2022-12-06 02:42
I'm guessing the issue is updating the manifest.json without pushing the 1.3.0 tag up
Obsidian is throwing a 404 trying to update/install

**Comment by SebastianMC** [comment] 2022-12-06 08:02
Yup, I've updated the files (incl. manifest) in master branch yet left the 1.3.0 release in a 'draft' state, not publishing it. I was not aware that Obsidian reads the manifest from master branch of the repository.

Fixed now, the release 1.3.0 is available and can be installed (from scratch or as an update)

Thanks for catching and reporting the problem and sorry for confusion and troubles!

**Comment by merlinuwe** [comment] 2022-12-06 11:23
The problem is solved, thank you very much!

**Comment by SebastianMC** [comment] 2022-12-06 16:53
Thanks for reporting the problem so quickly and also diagnosing it! It allowed also a quick resolution.

**Closed by SebastianMC** 2022-12-06 16:53 UTC
